// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIza' 'Sy' 'CU20_OxIaSznk-jJhFvwifhDR3uTEFFZc',
    appId: '1:937726428403:web:fdc0581e9dffd8e4e9a386',
    messagingSenderId: '937726428403',
    projectId: 'rehab-3b9a9',
    authDomain: 'rehab-3b9a9.firebaseapp.com',
    storageBucket: 'rehab-3b9a9.firebasestorage.app',
    measurementId: 'G-3W3ZDW74ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza' 'Sy' 'C3TFDbxHv067BAkAQlkaKbRRRyrTyesFs',
    appId: '1:937726428403:android:fae5f541cdfc6b53e9a386',
    messagingSenderId: '937726428403',
    projectId: 'rehab-3b9a9',
    storageBucket: 'rehab-3b9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza' 'Sy' 'CtoGIDnUKc2fSG7E6m3GKyFFpS2p4WhN4',
    appId: '1:937726428403:ios:944a1518d9ff2110e9a386',
    messagingSenderId: '937726428403',
    projectId: 'rehab-3b9a9',
    storageBucket: 'rehab-3b9a9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza' 'Sy' 'CtoGIDnUKc2fSG7E6m3GKyFFpS2p4WhN4',
    appId: '1:937726428403:ios:944a1518d9ff2110e9a386',
    messagingSenderId: '937726428403',
    projectId: 'rehab-3b9a9',
    storageBucket: 'rehab-3b9a9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIza' 'Sy' 'CU20_OxIaSznk-jJhFvwifhDR3uTEFFZc',
    appId: '1:937726428403:web:0e6a17b5a8a47a1ae9a386',
    messagingSenderId: '937726428403',
    projectId: 'rehab-3b9a9',
    authDomain: 'rehab-3b9a9.firebaseapp.com',
    storageBucket: 'rehab-3b9a9.firebasestorage.app',
    measurementId: 'G-HW0D0G05P9',
  );
}
